### ISSUE TITLE
Ng5-slider shrinks while loading in safari and mozila firefox

### ISSUE THREAD

**Issue by jrnjerin** [angular-slider/ngx-slider#138]
Hello,
I am using ng5-slider component. It is working fine in google chrome and opera but not in Safari and firefox. All the slider options are appearing on the first slider option. Lets say there are 3 slider options , then all are placed on top of other to the left most slider option.
Please help.

**Comment by epasch** [comment]
I ran into the same issue on an iPhone XR and Desktop Firefox. My "fix" was to force a manual refresh after I displayed the slider.

https://angular-slider.github.io/ng5-slider/demos#manual-refresh-slider

**Comment by piotrdz** [comment]
As answered above, this is a [known limitation of some browser versions](https://github.com/angular-slider/ngx-slider/blob/master/KNOWN_ISSUES.md#slider-is-not-refreshing-when-used-in-a-dynamic-component). It should be fixed with newer browser versions that support ResizeObserver API, in this case Firefox >= 69 and Safari >= 13.4. Otherwise, the workaround is to use `manualRefresh`.
