### ISSUE TITLE
The `with-legend` class is never set

### ISSUE THREAD

**Issue by dana-c0914** [angular-slider/ngx-slider#170]
Hi,

I would like to add some styling on the first and last tick legend as seen on the slider. This seems to be impossible right now because the `tick` elements that contain the legend seem to be always added in the `ticks` container in the ascending order of the values, instead of being added in the order they are seem on the slider. 

As a concrete example:
If I have on the slider the following values, in this order: 0, 25, 50, 75, 100, the ticks elements will be in the same order, meaning the first will be the tick containing the legend for value 0, the second will be the tick containing the legend for value 25 and so on.
But the problem is that if I have the values 100, 75, 50, 25, 0 on the slider, in this order, the ticks will be in the same order as before, meaning the first tick from the container is the one containing the legend for the value 0.

What I am really trying to achieve in the end with the styling is to make the legend for the first and last tick stay inside of the slider bounds. I tried using the `boundPointerLabels` options but it doesn't work, I guess it's for the values.

So if you have any idea how I could get around to do this I am happy to hear it.
Thanks in advance.

**Comment by piotrdz** [comment]
Yes, the `with-legend` class was not applied to the slider as it should have been. I fixed that in current master.

> But the problem is that if I have the values 100, 75, 50, 25, 0 on the slider, in this order, the ticks will be in the same order as before, meaning the first tick from the container is the one containing the legend for the value 0.
If you are talking about using rightToLeft flag, then yes, it works this way - the position of ticks is reversed, but the order in which they appear in HTML stays the same. I have no plans to change that.

As for the other question about styling ticks, currently, the ticks are free elements, added under ticks, and they are not positioned in any way relative to the slider bounds. I am not sure if I want to go that far with this, because positioning labels correctly is enough of pain as it is.

**Comment by piotrdz** [comment]
Released in v2.0.3. Closing.
