### ISSUE TITLE
Support Angular 13+ (Ivy distribution)

### ISSUE THREAD

**Issue by jefbarn** [angular-slider/ngx-slider#296]
From Angular 13:

Processing legacy "View Engine" libraries:
- @angular-slider/ngx-slider [es2015/esm2015] (https://github.com/angular-slider/ngx-slider.git)
Encourage the library authors to publish an Ivy distribution.

**Comment by mateusz-sawit** [comment]
Seems to be done on fork https://github.com/rp3e11/ngx-slider

**Comment by rp3e11** [comment]
Yes I forked it and upgrade it to v13. 

It works fine in my project, but I have to do further testing. To upgrade I also had to upgrade the demo-app which seems fine at first glance but I have check it in more detail. 

I had one issue with performance since ngUpdate called updateTicks which in turn calls detectChanges() and that lead to infinite callback loop. I moved detectChanges inside an if statement such that it is only called if the ticks are changed. This might be a problem for other uses and I have to investigate that further.

I didn't manage to run the e2e tests yet, but that seems to be related to a version mismatch between chromium driver and my installed chrome, so I could't execute the tests.

**Comment by rp3e11** [comment]
I had another look at the remaining work to finish the upgrade to v13. 

The state right now is, that I can install and work with the slider in my project. However, I only use a subset of all the features so I have no clue, whether there are any remaining issues for all the other features. Further the demo-app in particular the typedoc documentation isn't properly working after the upgrade. The way I see it right now, there are three tasks that would have to be completed before it could be merged back:

- As mentioned I didn't manage to run the e2e tests and given some further research it seems to be related to the deprecation of protractor. So it might make more sense to move to a new testing framework for the e2e tests. I could move the testing to cypress.
- Bug fixing: Fix bugs that might be caused in other use cases that I have not used in my project. 
- typedoc is used in an old version that causes some issues with angular 13. I started the upgrade of typedoc to the latest version, but it is not done.

Fixing all the above will take a significant amount of time. I could do the bulk of the work, but before I would start it, I would have to be sure, that it would be merged back by the maintainers and that they are happy with the breaking upgrades from protractor to cypress and typedoc. Is there a maintainer who would do that?

**Comment by jymaps** [comment]
Does the fork solves the issue? How do I use it in my project? Is it enough to run `ng build`?

**Comment by jymuk** [comment]
@rp3e11 Can you help me out please with a guide on how to install this fork in our app?

**Comment by rp3e11** [comment]
Sorry for the late reply. 

I am not working with this fork anymore since I haven't heard back from maintainers and the library is quite complex and I don't understand the implementation to a high enough level, that I could maintain it myself (i.e. fix bugs). So I wouldn't recommend using my fork in the long run.

If you still want to use it, there are a couple of options. The easiest one (in my opinion) is to clone it and use npm link as described in this stackoverflow [thread](https://stackoverflow.com/questions/58374143/how-to-include-a-local-library-in-angular). The build instructions are in the file DEVELOPERS.md.

**Comment by danisss9** [comment]
Hello, 

I created a fork with Angular 14/15 support based on @rp3e11 fork. In case you want to use it https://www.npmjs.com/package/ngx-slider-v2
https://github.com/danisss9/ngx-slider

**Comment by vinlos** [comment]
> Hello,
> 
> I created a fork with Angular 14/15 support based on @rp3e11 fork. In case you want to use it https://www.npmjs.com/package/ngx-slider-v2 https://github.com/danisss9/ngx-slider

Thank you for your work. If you need help in maintaining this package, don't hesitate to contact me

**Comment by whyboris** [comment]
✅  confirming that [danisss9/ngx-slider](https://github.com/danisss9/ngx-slider) _Fork_ works with Angular 16 🚀

**Comment by ananthay** [comment]
are there any plans of merging [danisss9/ngx-slider](https://github.com/danisss9/ngx-slider) ?

**Comment by piotrdz** [comment]
Closing old issues about the same subjects. Please follow discussion in more recent issues regarding this subject (https://github.com/angular-slider/ngx-slider/issues/351, https://github.com/angular-slider/ngx-slider/issues/355).
