### ISSUE TITLE
Do you need help maintaining this pakage

### ISSUE THREAD

**Issue by santoshyadavdev** [angular-slider/ngx-slider#351]
Hey @rzajac @piotrdz and @ValentinH  do you need any help maintaining this package, I can see this package is used by many and has close to 90k downloads per week.

I would be happy to maintain this package if you want.

**Comment by ValentinH** [comment]
On my side, I've never used Angular since v2 started so that's why I'm 'ot maintaining this project. 
@piotrdz is the guy with all the credits here.

However, maintenance is a complex topic because, no offense, but I don't think we should give maintainance ownership to someone with no previous contributions on this project. Indeed, there have unfortunately be occurrences in the past in the NPM ecosystem of libraries take over and ending up with malwares.

That being said, if you believe that some things should be added or fixed to this repository, I think opening PRs is a good start if @piotrdz as the time to review them. Managing issues is also a good way to contribute.

**Comment by santoshyadavdev** [comment]
Fare enough, I will raise a PR to upgrade in upcoming weeks.

**Comment by piotrdz** [comment]
As I explained in issue #306, I no longer plan to actively develop this project either. Although I said I would do one last upgrade to newer Angular version in my comment, I actually never got to finish that. As usual, life got in the way.

Since then, I can see that some people have created their own forks with upgrades in issue #296. I will have to think about what to do. I might pull in their work, or try to do another upgrade myself.

Other than that, I may look at pull requests, if they address specific issues, but in general I will be stepping away from active maintenance. The actual work of sorting out and fixing issues would have to go to other volunteers.

**Comment by ashwanikrsingh** [comment]
Hi @piotrdz and @santoshyadavdev ,
Is there any update here ? It would be very kind of you, if you guys can release a new version which is compatible with Angular Ivy.

**Comment by visuallization** [comment]
Adding new trustable admins to the project seems like a good idea.

**Comment by piotrdz** [comment]
Hello everyone.

I am sorry I have been neglecting this project so long. There is a reason behind it, tied to my health, both physical and mental.

Fortunately, thanks to some amazing people, I have made good progress on getting my health back, and now, I would like to return to things that I have let lapse, like this project.

I am very much open to the idea of passing the admin to another trusted person. However, like @ValentinH mentioned above, it needs to be carefully thought out.

Having said that, I would like to move this discussion to a place that is better for real-time communication. Therefore, I have started a Discord server called **ngx-slider**. It is open to everyone wishing to discuss anything regarding this project. Please join the server using the link below:

https://discord.gg/C6K9S9r7

**Comment by ValentinH** [comment]
Hey @piotrdz . I'm glad that you are feeling better, it's good to read this!
Wish you all the best for the future 🥳

**Comment by visuallization** [comment]
@piotrdz That sounds great! Thank you for opening up the discussion!! Also glad that you are feeling better!

**Comment by piotrdz** [comment]
As referenced earlier, I am going to keep the discussions on project governance to the Discord server. Github is good as an issue tracker, but lacks the real-time communication offered by services like Discord.

The link to Discord is now published in the README and should be readily accessible to everyone.

Therefore, closing this issue here.
